program tt(input);
 type ii = packed record
	  xx, yy, oo34: integer;
	  yy          : real;
	  case  bit : char of
		  'a','b': (xx :char);
		  'z':     (yy :record
				  xx, yy, oo34: integer;
				  yy          : real;
				  case  bit : char of
				     'a','b': (xx :char);
				     'z':     (yy :integer )
				end
			       )
	  end;
var   ii,j34:integer; jjj33:real;
      jj: array [2 .. 3] of array [1 .. 121] of real;
begin ii.xx:=((6+3.38- 55 /23)*ii div 6)+[44/3 .. ttt, 44 and 33];
      if (xx > yy) then if hh <= 3 then hh:=4 else hh:=hh/5 else hh:=7;
      if (xx > yy) then if hh < 3 then hh:=4 else hh:=hh/5 ;
      if (xx > yy) then if hh >= 3 then hh:=4
end.