program tt(input);
var   ii,j34:integer; jjj33:real;
      jj: array [2 .. 3] of array [1 .. 121] of real;
begin ii.xx:=((6+3.38- 55 /23)*ii div 6);
      if (xx > yy) then if hh <= 3 then hh:=4 else hh:=hh/5 else hh:=7;
      if (xx > yy) then if hh < 3 then hh:=4 else hh:=hh/5 ;
      if (xx > yy) then if hh >= 3 then hh:=4;
	a:=0;
	b:=10;
	c:=a+b;
	for i:=2 to b do begin
            if (xx > yy) then
		if hh < 3 then hh:=4
		else a:=hh/5 ;
            if (xx > yy) then if hh >= 3 then hh:=4;
	for j:=2 to b do begin
            if (xx > yy) then
		if hh < 3 then hh:=4
		else hh:=hh/5 ;
            if (b > c) then if hh >= 3 then hh:=4;

        end;
        end;
end.